### PR TITLE
added two javascript algorithms (after syncing with main branch)

### PR DESCRIPTION
**Pull request by thesmallplanet**
maximum subarray & recursive bubble sort

### CODE REVIEW

**Review by amilajack — CHANGES_REQUESTED** [review]
rebase against `main` so tests will run

**Comment by thesmallplanet** [comment]
like that?

**Comment by amilajack** [comment]
```
git rebase upstream/main
git push origin main -f
```

**Comment by thesmallplanet** [comment]
done, thanks for updating the test workflow!

**Review by amilajack — APPROVED** [review]

**Pull request merged**
