### PR TITLE
Implement djikstra shortest path algorithm

### PR DESCRIPTION
**Pull request by nourrrrrrrr**

### CODE REVIEW

**Comment by nourrrrrrrr** [comment]
I think its done.

**Comment by nourrrrrrrr** [comment]
I think its done but All checks have failed.

**Comment by nourrrrrrrr** [comment]
> Please rename this file to a `.js` file

I think its done but All checks have failed.

**Comment by nourrrrrrrr** [comment]
> Please rename this file to a `.js` file

Its done but i cant find why the checks have failed.

**Comment by jooohhn** [comment]
@nourrrrrrrr if you click on the CI check you can see why it failed: https://dev.azure.com/amilajack/amilajack/_build/results?buildId=9321&view=logs&j=43d32c17-ff19-5d0a-58b3-52a09bf40d57&t=b0530c04-46b0-522d-ec87-b4f85da9830d&l=351

**Comment by amilajack** [comment]
@nourrrrrrrr What text editor are you using? Try installing the extensions for your text editor here: https://electron-react-boilerplate.js.org/docs/editor-configuration. They will help you see what the errors are and how to fix them.

**Pull request closed without merging**
